/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.organizador;

import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class frGerenciador extends javax.swing.JFrame {

    /**
     * Creates new form frGerenciador
     */
    public frGerenciador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTarefa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLista = new javax.swing.JTextArea();
        btnSetTarefa = new javax.swing.JButton();
        btnAddTarefa = new javax.swing.JButton();
        btnRemoveTarefa = new javax.swing.JButton();
        btnSortLista = new javax.swing.JButton();
        btnTamanhoLista = new javax.swing.JButton();
        btnRemoveAll = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtTarefa.setBackground(new java.awt.Color(255, 255, 255));
        txtTarefa.setForeground(new java.awt.Color(0, 0, 0));
        txtTarefa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTarefa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTarefaMouseClicked(evt);
            }
        });
        txtTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarefaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tarefa");

        txtLista.setEditable(false);
        txtLista.setBackground(new java.awt.Color(255, 255, 255));
        txtLista.setColumns(20);
        txtLista.setForeground(new java.awt.Color(0, 0, 0));
        txtLista.setRows(5);
        txtLista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jScrollPane1.setViewportView(txtLista);

        btnSetTarefa.setBackground(new java.awt.Color(255, 255, 0));
        btnSetTarefa.setForeground(new java.awt.Color(0, 0, 0));
        btnSetTarefa.setText("Alterar Tarefa");
        btnSetTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetTarefaActionPerformed(evt);
            }
        });

        btnAddTarefa.setBackground(new java.awt.Color(51, 255, 51));
        btnAddTarefa.setForeground(new java.awt.Color(0, 0, 0));
        btnAddTarefa.setText("Adcionar Tarefa");
        btnAddTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTarefaActionPerformed(evt);
            }
        });

        btnRemoveTarefa.setBackground(new java.awt.Color(255, 0, 51));
        btnRemoveTarefa.setForeground(new java.awt.Color(0, 0, 0));
        btnRemoveTarefa.setText("Remover Tarefa");
        btnRemoveTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveTarefaActionPerformed(evt);
            }
        });

        btnSortLista.setText("Organizar Lista");
        btnSortLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortListaActionPerformed(evt);
            }
        });

        btnTamanhoLista.setText("Tamanho Lista");
        btnTamanhoLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamanhoListaActionPerformed(evt);
            }
        });

        btnRemoveAll.setBackground(new java.awt.Color(255, 0, 51));
        btnRemoveAll.setForeground(new java.awt.Color(0, 0, 0));
        btnRemoveAll.setText("Apagar tudo");
        btnRemoveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTarefa)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(btnSetTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemoveTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSortLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTamanhoLista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemoveAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddTarefa)
                        .addGap(18, 18, 18)
                        .addComponent(btnSetTarefa)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveTarefa)
                        .addGap(18, 18, 18)
                        .addComponent(btnSortLista)
                        .addGap(18, 18, 18)
                        .addComponent(btnTamanhoLista)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveAll)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciador de Tarefas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Tarefa t = new Tarefa();
    private void btnSetTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetTarefaActionPerformed
        String indiceSTR = JOptionPane.showInputDialog("Insira o Indice");
        String novaTarefa = JOptionPane.showInputDialog("Insira a nova tarefa");
        if (indiceSTR == null || (indiceSTR != null && ("".equals(indiceSTR))) || novaTarefa == null || (novaTarefa != null && ("".equals(novaTarefa)))) {
            JOptionPane.showMessageDialog(null, "Nenhum indice ou Tarefa inserido(a)");
        } else {
            int indice = Integer.parseInt(indiceSTR);
            if (indice > t.getQuantidadeTarefas() || indice < 0) {
                JOptionPane.showMessageDialog(null, "indice inexistente");
            } else {
                t.editTarefa(indice, novaTarefa);
                txtLista.setText(t.getTarefas());
            }
        }
    }//GEN-LAST:event_btnSetTarefaActionPerformed

    private void btnAddTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTarefaActionPerformed
        if (txtTarefa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nenhuma tarefa inserida!");
        } else {
            t.addTarefa(txtTarefa.getText());
            txtLista.setText(t.getTarefas());
        }
    }//GEN-LAST:event_btnAddTarefaActionPerformed

    private void btnRemoveTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveTarefaActionPerformed
        String indiceSTR = JOptionPane.showInputDialog(null, "Insira o Indice");
        if (indiceSTR == null || (indiceSTR != null && ("".equals(indiceSTR)))) {
            JOptionPane.showMessageDialog(null, "Nenhum indice inserido!");
        } else {
            int indice = Integer.parseInt(indiceSTR);
            if (indice >= t.getQuantidadeTarefas() || indice < 0) {
                JOptionPane.showMessageDialog(null, "indice inexistente");
            } else {
                t.removeTarefa(indice);
                txtLista.setText(t.getTarefas());
            }
        }
    }//GEN-LAST:event_btnRemoveTarefaActionPerformed

    private void btnSortListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortListaActionPerformed
        if (t.ListaVazia()) {
            JOptionPane.showMessageDialog(null, "A lista esta vazia");
        } else {
            t.sortTarefas();
            txtLista.setText(t.getTarefas());
        }
    }//GEN-LAST:event_btnSortListaActionPerformed

    private void btnTamanhoListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamanhoListaActionPerformed
        JOptionPane.showMessageDialog(null, t.getQuantidadeTarefas());
    }//GEN-LAST:event_btnTamanhoListaActionPerformed

    private void btnRemoveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAllActionPerformed
        if (t.ListaVazia()) {
            JOptionPane.showMessageDialog(null, "a lista esta vazia");
        } else {
            t.removeAllTarefas();
            txtLista.setText(t.getTarefas());
        }
    }//GEN-LAST:event_btnRemoveAllActionPerformed

    private void txtTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarefaActionPerformed
        t.addTarefa(txtTarefa.getText());
        txtLista.setText(t.getTarefas());
        txtTarefa.requestFocus();
        txtTarefa.selectAll();
    }//GEN-LAST:event_txtTarefaActionPerformed

    private void txtTarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTarefaMouseClicked
        txtTarefa.selectAll();
    }//GEN-LAST:event_txtTarefaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frGerenciador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTarefa;
    private javax.swing.JButton btnRemoveAll;
    private javax.swing.JButton btnRemoveTarefa;
    private javax.swing.JButton btnSetTarefa;
    private javax.swing.JButton btnSortLista;
    private javax.swing.JButton btnTamanhoLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtLista;
    private javax.swing.JTextField txtTarefa;
    // End of variables declaration//GEN-END:variables
}
